version: '3.8'

services:
  flask-app:
    build: ./app
    container_name: flask_app
    restart: always
    ports:
      - "5000:5000"
    networks:
      - my_network
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: default_db
      MYSQL_USER: default_user
      MYSQL_PASSWORD: default_password
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data:
